name: platapp_flutter
description: Platapp Is Made with â¤ in flutter at KarmaLn Techbology.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4


  # Responsive layout helper (text,height,width)
  responsive_sizer: ^3.0.5+1

  #ImageSlider
  carousel_slider: ^4.0.0

  # Animation Packages
  animated_widgets: ^1.1.0
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  #set app icon
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher-Regular.ttf
        - asset: assets/fonts/Philosopher-Bold.ttf
        - asset: assets/fonts/Philosopher-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Philosopher-Italic.ttf
          style: italic

  uses-material-design: true


