name: platapp_flutter
description: Platapp Is Made with â¤ in flutter at KarmaLn Techbology.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  permission_handler: ^9.2.0


  # Responsive layout helper (text,height,width)
  responsive_sizer: ^3.0.5+1

  #Image-Slider / Image Providers
  carousel_slider: ^4.0.0
  flutter_svg: ^1.0.3

  # Animation Packages
  animated_widgets: ^1.1.0
  lottie: ^1.3.0

  #Bottom Bar
  persistent_bottom_nav_bar_v2: ^4.1.9
  #camara access
  camera: ^0.9.4+19
  video_player: ^2.3.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  #set app icon
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/applogo.png"

flutter:
  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
    - assets/

  fonts:
    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher-Regular.ttf
        - asset: assets/fonts/Philosopher-Bold.ttf
        - asset: assets/fonts/Philosopher-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Philosopher-Italic.ttf
          style: italic

  uses-material-design: true


